[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
#[templates.placeholder]
#input_path = "/nix/store/qrppp5azmc4hawx8b6wrl3qv7xqplm28-noctalia-shell-2026-01-12_ef70775/share/noctalia-shell/Assets/MatugenTemplates/noctalia.json"
#output_path = "/home/alex/.cache/noctalia/placeholder.json"

[templates.kitty]
input_path = "~/.config/noctalia/colorschemes/kitty.conf"
output_path = "~/.config/kitty/themes/noctalia.conf"
post_hook = "pkill -SIGUSR1 kitty"
